author: 'Drmmsu' # 作者名称
author_avatar: /drmmsu/about/me/avatar.jpg # 作者头像
author_text: '我的学习笔记' # 作者信息
social: # 社交链接
  # - title: 'Github'
  #   icon: 'github'
  #   link: ''
  - title: '首页'
    icon: 'home'
    link: 'https://zhangluting123.github.io/drmmsu/'
# background: 'https://api.paugram.com/wallpaper?source=gh' # 主题背景
menu: # 页眉菜单项目
  '关于我': /about/me
config:
  copyright: true # 复制的时候弹出保留原站链接说明
  night: false # 自动切换夜间模式
